import java.util.ArrayList;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Dealer.java
//  @ Date : 04/10/2013
//  @ Author : 
//
//




/** */
public class Dealer
{
	/** */
	private String name;
	
	private	List<Customer> customerList = new ArrayList<Customer>();
	
	/** */
	private	List<Employee> employeeList = new ArrayList<Employee>();
	
	/** */
	private	List<Vehicle> vehicleList = new ArrayList<Vehicle>();
	
	/** */
	
	public Dealer(String name) {
		// TODO Auto-generated constructor stub
		this.name = name;
	}

	/** */
	public void getEmployeeDetails()
	{
	
	}
	
	/** */
	public void getVehicleDetails()
	{
	
	}

	public void addEmployee(Employee employee) {
		// TODO Auto-generated method stub
		this.employeeList.add(employee);
		
	}

	public void addVehicle(Vehicle vehicle) {
		// TODO Auto-generated method stub
		this.vehicleList.add(vehicle);
	}
}
