//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Employees.java
//  @ Date : 04/10/2013
//  @ Author : 
//
//
import java.util.Date;



/** */
public class Employee
{
	/** */

	
	private String name;
	
	/** */
	private Date DateOfJoin;
	
	/** */
	private Date DOB;
	
	
	/** */
	public Dealer dealer;
	
	public Employee(String name, Date dateOfJoin, Date DOB, Dealer dealer) {
		// TODO Auto-generated constructor stub
	this.name= name;
	this.DateOfJoin = dateOfJoin;
	this.DOB = DOB;
	this.dealer = dealer;
	}

	/**
	 * @return  */
	public String getName()
	{
		return this.name;
	}
	
	/**
	 * @return  */
	public Date getDateOfJoin()
	{
	   return this.DateOfJoin;
	}


}
