//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : InsuranceCompany.java
//  @ Date : 04/10/2013
//  @ Author : 
//
//

/** */
public class InsuranceCompany {

	// private Reciept reciept;
	public boolean createInsurance(Insurance insurance) {
		// TODO Auto-generated method stub
		System.out.println("insurance Created");
		Reciept reciept = new Reciept();
		reciept.generateInsuranceReciept(insurance);
		return true;

	}

}
