//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Reciept.java
//  @ Date : 04/10/2013
//  @ Author : 
//
//

/** */
public class Reciept {
	/** */
	private Insurance insurance;
	private Registration registration;

	public void generateRegistrationReceipt(Registration registration) {
		// TODO Auto-generated method stub
		this.registration = registration;
		registration.diplayDetails();
	}

	public void generateInsuranceReciept(Insurance insurance) {
		// TODO Auto-generated method stub
		this.insurance = insurance;
		insurance.diplayDetails();
	}

}
