import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SalesRepresentative extends Employee {
	//
	//
	// Generated by StarUML(tm) Java Add-In
	//
	// @ Project : Untitled
	// @ File Name : SalesRep..java
	// @ Date : 04/10/2013
	// @ Author :
	//
	//

	/** */

	/** */
	private List<Customer> customerList = new ArrayList<Customer>();

	/** */
	private List<Vehicle> vehicleList = new ArrayList<Vehicle>();

	/** */
	// public Employe;

	/** */

	/** */

	/** */
	public Insurance insurance;

	private Registration registration;

	private SalesDepartment salesdepartment;

	public SalesRepresentative(String name, Date dateOfJoin, Date DOB, Dealer dealer) {
		// TODO Auto-generated constructor stub
		super(name, dateOfJoin, DOB, dealer);
		this.salesdepartment = new SalesDepartment();

	}

	/**
	 * @param vehicle
	 * @param customer
	 * @param insurancecompany
	 */
	public void insurevehicle(Customer customer, Vehicle vehicle, InsuranceCompany insurancecompany) {
		if (!checkVehicleregistration(vehicle))
			System.out.println("Vehicle must be first registered");
		else {

			this.insurance = new Insurance(customer, vehicle, this, insurancecompany);
			Policy policy = customer.getPolicydetails();
			this.insurance.setPlicydetails(policy);
			Payment payment = customer.getPaymentdetails(this.insurance);
			this.insurance.setpaymentDetails(payment);
			if (insurancecompany.createInsurance(this.insurance)) {
				vehicle.setInsurancedetails(insurance);
				customer.setVehicledetails(vehicle);
			}

		}

	}

	private boolean checkVehicleregistration(Vehicle vehicle) {
		// TODO Auto-generated method stub
		Registration reg = vehicle.getRegdetails();
		if (vehicle.getRegdetails() == null)
			return false;
		else
			return true;

	}

	public void renewInsurance(Customer customer) {
		// TODO Auto-generated method stub
		Vehicle vehicle = customer.getVehicledetails();
		this.insurance = vehicle.getInsurancedetails();
		this.insurance.renew(customer.getPaymentdetails(this.insurance), customer.getPolicydetails(), this);

	}

	public void registervehicle(Customer customer, Vehicle vehicle, RTODepartment rtodepartment) {
		// TODO Auto-generated method stub

		if (checkVehicleregistration(vehicle))
			System.out.println("Vehicle is already  registered");
		else {
			customerList.add(customer);
			vehicleList.add(vehicle);
			this.registration = new Registration(customer, vehicle, this, rtodepartment);
			Payment payment = customer.getPaymentdetails(this.registration);
			this.registration.setpaymentDetails(payment);
			if (rtodepartment.RTOregisterVehicle(this.registration)) {
				vehicle.setRegistrationdetails(this.registration);
				customer.setVehicledetails(vehicle);
			}

			this.salesdepartment.setRegisterDetails(vehicle);
		}
	}
}
