//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Insurance.java
//  @ Date : 04/10/2013
//  @ Author : 
//
//
import java.util.Date;



/** */
public class Insurance
{
	/** */
	//private String insuranceNo;
	
	/** */
//	private String insuranceType;
	
	/** */
	private Employee employeeDetails ;
	
	/** */
//	private Date dueDate;
	
	/** */
	
	
	/** */
	private Policy policyDetails;
	
	/** */
	//private int ammount;
	
	/** */
	private Customer customerDetails ;
	
	/** */
	private  Payment payment ;
	
	private Vehicle vehicleDetails;
	/** */

	/** */

	
	/** */
	private InsuranceCompany insurancecompany;
	
	private Registration registration;
	public Insurance(Customer customer, Vehicle vehicle, SalesRepresentative salesRepresentative, InsuranceCompany insurancecompany) {
		// TODO Auto-generated constructor stub
		this.customerDetails = customer;
		this.vehicleDetails = vehicle;
		this.employeeDetails= salesRepresentative;
		this.insurancecompany = insurancecompany;
	
	}

	/** */
	public void getPolicyDetails()
	{
	
	}
	
	/** */


	public void setPlicydetails(Policy policy) {
		// TODO Auto-generated method stub
		this.policyDetails = policy;
		
	}

	public void setpaymentDetails(Payment payment) {
		// TODO Auto-generated method stub
		this.payment = payment;
	}

	public void diplayDetails() {
		// TODO Auto-generated method stub
		System.out.println("________________________________________________________________________");
		System.out.println("INSURANCE DETAILS");
		System.out.println("Vehicle Registion Number:"+this.vehicleDetails.getRegdetails().getregistrationNo());
		System.out.println("Vehicle Model:"+this.vehicleDetails.getModel());
		System.out.println("Vehicle Type:"+this.vehicleDetails.getType());
		System.out.println("Customer Details");
		System.out.println("customer Name"+this.customerDetails.getName());
		System.out.println("contact Number"+this.customerDetails.getContactinfo());
		System.out.println("policy details"+this.policyDetails.getIssueddate());
		System.out.println(this.policyDetails.getDuedate());
		System.out.println(this.policyDetails.getPolicydescription());
		
	}

	public void renew(Payment paymentdetails, Policy policydetails, SalesRepresentative salesRepresentative) {
		// TODO Auto-generated method stub
		this.payment = paymentdetails;
		this.policyDetails = policydetails;
		this.employeeDetails = salesRepresentative;
		System.out.println("Renewed");
		
	}

	
}
