//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Payment.java
//  @ Date : 04/10/2013
//  @ Author : 
//
//
import java.util.Date;




/** */
public class Payment
{
	private Registration registration;

	public Payment(String payementMode, Date date, SalesRepresentative salesRep,
			Customer customer, Insurance insurance) {
		// TODO Auto-generated constructor stub
		this.paymentMode = payementMode;
		this.Date = date;
		this.employee = salesRep;
		this.customer = customer;
		this.insurance = insurance;
		
	}

	public Payment(String payementMode, Date date,
			SalesRepresentative salesRep, Customer customer,
			Registration registration) {
		// TODO Auto-generated constructor stub
		this.paymentMode = payementMode;
		this.Date = date;
		this.employee = salesRep;
		this.customer = customer;
		this.registration = registration;
	}

	/** */
	private String paymentMode;
	
	/** */
	private Date Date;
	
	/** */
	public Employee employee;
	
	/** */
	public Customer customer;
	
	/** */
	
	
	/** */
	public Insurance insurance;
	
	/** */
//	public InsuranceCompany insuranceCompany;
	
	/** */
	
	
	/** */

}
