//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Vehicle.java
//  @ Date : 04/10/2013
//  @ Author : 
//
//




/** */
public class Vehicle
{
	/** */
	private Registration registration;
	
	/** */
	private int capacity;
	 
	private String chasisNumber;
	
	private String color;
	
	private String vehicleType;
	
	private String vehicleName;
	/** */
	private String fuelType;
	
	private Insurance insurance;
	
	
	/** */
	
	
	public Vehicle(int capacity, String chasisNumber, String color, String vehicleType,
			String fuelType,String vehicleName) {
		// TODO Auto-generated constructor stub
		this.capacity = capacity;
		this.chasisNumber = chasisNumber;
		this.color = color;
		this.vehicleType = vehicleType;
		this.fuelType = fuelType;
		this.vehicleName=vehicleName;
		
		}

	/** */
	public Registration getRegdetails()
	{
		return this.registration;
	}
	
	/** */
	public void getOwner()
	{
	
	}

	public void setInsurancedetails(Insurance insurance) {
		// TODO Auto-generated method stub
		this.insurance = insurance;
		
	}

	public Insurance getInsurancedetails() {
		// TODO Auto-generated method stub
		return this.insurance;
	}

	public String getModel() {
		// TODO Auto-generated method stub
		return this.vehicleName;
	}

	public String getType() {
		// TODO Auto-generated method stub
		return this.vehicleType;
	}

	public void setRegistrationdetails(Registration registration) {
		// TODO Auto-generated method stub
		this.registration = registration;
	}
}
